Practice 6.1 6.2 - William Eduardo Guarneros
breakponchito/JavaOCA_8_gen_2020 pull request #1
Opened 2020-06-16 02:44 UTC by weduardogs

Cambios de las prácticas 6.1 y 6.2

2020-06-16 16:26 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/deveduardodogs/soccer_game_6_1_6_2/Game.java
> +package com.cert.oca8.course.deveduardodogs.soccer_game_6_1_6_2;
Puedes seguir la siguiente recomendación para ajustar todos los paquetes:
deveduardodogs->module6->practice1->contenido clases practica 1
deveduardodogs->module6->practice2->contenido clases practica 2

con eso quedara mejor estructurado tu código y hay que seguir esa recomendación para las posteriores practicas

2020-06-16 16:26 UTC, breakponchito requested changes
Ajustar los paquetes y borrar los archivos class

2020-06-16 16:28 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/deveduardodogs/soccer_game_6_1_6_2/League.java
> +import java.sql.SQLOutput;
Hay que remover este import que no es utilizado

2020-06-17 17:42 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/deveduardodogs/module6/practice1/Player.java
> +
checar la guia de estudiante desde la pagina 17 y en adelante para agregar el contenido relacionado a  esta clase, falta sus fields

2020-06-17 17:42 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/deveduardodogs/module6/practice1/Team.java
> +
checar la guía de estudiante desde la pagina 17 y en adelante para agregar el contenido relacionado a esta clase, falta sus fields

2020-06-17 18:26 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/deveduardodogs/module6/practice2/Player.java
> +    public String number;
en vez de crear la misma clase en dos paquetes distintos, lo mejor sera que reutilices la clase de la practica1. La recomendación es que para que funcione debes de importar la clase del otro paquete. Realiza esto mismo para las clases de la practica1 que se van a utilizar en la practica2 del modulo 6

2020-06-18 02:45 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/deveduardodogs/module6/practice1/Player.java
> +    public String playerNumber;
Esta propiedad aun no se solicito para ingresar

2020-06-18 03:08 UTC, weduardogs commented on src/main/java/com/cert/oca8/course/deveduardodogs/module6/practice1/Player.java
> +    public String playerNumber;
Sí, lo sé. Sólo estaba practicando con más propiedades. La elimino sin problema

2020-06-18 03:13 UTC, weduardogs commented on src/main/java/com/cert/oca8/course/deveduardodogs/module6/practice1/Player.java
> +    public String playerNumber;
Propiedad eliminada

2020-06-19 00:31 UTC, weduardogs commented
Hice un par de cambios, seguí las indicaciones de la guía.

2020-06-19 01:23 UTC, breakponchito approved these changes
LGTM

2020-06-19 01:23 UTC, merged