Branch dev munguia
breakponchito/JavaOCA_8_gen_2020 pull request #2
Opened 2020-06-16 03:43 UTC by DanielMunguia95

Practice 6.1 and 6.2

2020-06-16 16:10 UTC, breakponchito commented on .gitignore
> +/target/
Muy bien por haber agregado la configuracion .gitignore y evitar subir los archivos class

2020-06-16 16:11 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/Game.java
> +   public Goal[] goals ;
hay un espacio en blanco entre el nombre de la variable goals y el ;

2020-06-16 16:22 UTC, breakponchito commented
un ligero comentario que te agregue y en general bien

2020-06-16 16:23 UTC, breakponchito requested changes
un comentario ligero por arreglar y listo para hacer merge

2020-06-18 02:38 UTC, DanielMunguia95 commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/Game.java
> +   public Goal[] goals ;
Listo, se agrega el cambio y se da commit al branch de esta clase.
Gracias

2020-06-18 02:41 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice2/Player.java
> +public class Player {
en vez de tener dos Player definidos podemos reutilizar el inicial que no cambia

2020-06-18 02:52 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/Game.java
> +   public Team teamVisit;
la propiedad debe llamarse awayTeam

2020-06-18 02:52 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/Game.java
> +   public Team teamHome;
la propiedad debe llamarse homeTeam

2020-06-19 01:10 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/Team.java
> +    public Player[] players;
Deberia llamarse playerArray en vez de players

2020-06-19 01:11 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/Goal.java
> +    public Player ThePlayer;
Debe iniciar el nombre de una variable con minúscula

2020-06-19 01:14 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/League.java
> +            System.out.println("Team 2 " + player.playerName);
por el momento no era necesario agregar Team 2

2020-06-19 01:15 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/League.java
> +            System.out.println("Team 1 " + thePlayer.playerName);
Por el momento no era necesario agregar Team 1

2020-06-19 01:19 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/League.java
> +
este espacio no es necesario

2020-06-19 01:19 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/League.java
> +
este espacio no es necesario

2020-06-19 01:20 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/League.java
> +
este espacio no es necesario

2020-06-19 16:40 UTC, breakponchito commented on src/main/java/com/cert/oca8/course/devdamunguia95/module6/practice1/League.java
> +
Revisa la practica 1 en la parte donde se modifica la clase League. Para la practica 1 falta código aquí para crear el equipo dos y hacer el proceso de impresión en pantalla

2020-06-20 03:18 UTC, breakponchito approved these changes
LGTM

2020-06-20 03:18 UTC, merged